# Generated by Django 5.1.3 on 2024-12-06 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Minimo 0 estrelas'), django.core.validators.MaxValueValidator(5, 'Maximo 5 estrelas')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='filmes.filme')),
            ],
        ),
    ]
