# Generated by Django 5.1.3 on 2024-12-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atores', '0001_initial'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('atores', models.ManyToManyField(related_name='filmes', to='atores.ator')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filmes', to='generos.genero')),
            ],
        ),
    ]
